version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - save_cache:
        keys: "npm-packages"
        paths:
          - /
      - run: npm run lint
      
    test:  
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - run: npm i
        - restore_cache:
          keys: "npm-packages"
        - run: npm run test
    analyze:  
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - run: npm i
        - restore_cache:
          keys: "npm-packages"
        - run: npm audit
        

    
    
workflows:
  When_on fail:
    jobs: 
      - build
      - test:
        - requires: build
      - analyze:
        - requires: test